id: I843748A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:59:45+00:00'
last_modified: '2022-06-07T17:55:27.325509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1796
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་སྒྲུང་འགྲེལ་དང་གཏམ་རྒྱུད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B021:
      image_group_id: I1KG1862
      title: ''
      total_pages: 210
      order: 1
      base_file: B021.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
