id: P003149
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:43:37.602464
source_metadata:
  id: bdr:W1KG1796
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་སྒྲུང་འགྲེལ་དང་གཏམ་རྒྱུད་
  author: ''
  volumes:
    3f3ede33223042aca3a5727019f7138e:
      image_group_id: I1KG1862
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
